"""Write data.js for the thesis deck from the committed results of thesis-core (T17–T21).

Everything is read with `git show <commit>:<path>`, so the deck shows reviewed results only, whatever is in the working
tree. COMMIT is the T21 commit that passed review on 2026-10-09; move it when a later task passes review.
THESIS_CORE overrides the repository path.

  python thesis/make_data.py
"""
import csv
import io
import json
import os
import subprocess
from pathlib import Path

REPO = Path(os.environ.get('THESIS_CORE') or Path(__file__).resolve().parents[2] / '30_研究' / 'thesis-core')
COMMIT = '83c16bf'
MODELS = ['free', 'reserve', 'segment']
# final batch directories per the review records (00_总控/reviews/T18.md, T20.md)
FLAG = {'yupu': ['a0ab16fceb94', '49d2383872e7'],   # Okpo, MY-B task mix: K 5–40, K 45–150
        'yantai': ['b82aa19b22af']}                 # Yantai map rev 395: K 1–150
T18 = 'results/t18_report_d10b9015cd4d/t18_summary.json'
T20 = 'results/t20_report_c12289dfda9d/t20_summary.json'


def show(path):
    return subprocess.run(['git', '-C', str(REPO), 'show', f'{COMMIT}:{path}'], capture_output=True, check=True).stdout.decode('utf-8-sig')


def saturated(yard):
    rows = [r for d in FLAG[yard] for r in csv.DictReader(io.StringIO(show(f'results/{d}/curves.csv')))
            if r['scen'] == 'main' and r['level'] == 'saturated']
    Ks = sorted({int(r['K']) for r in rows})
    get = {(r['model'], int(r['K'])): r for r in rows}
    assert all((m, k) in get for m in MODELS for k in Ks), yard
    return {'K': Ks, **{m: [[round(float(get[m, k][f'throughput_{s}']), 1) for s in ('mean', 'lo', 'hi')] for k in Ks] for m in MODELS}}


def bounds(yard):
    rows = [r for r in csv.DictReader(io.StringIO(show(f'results/{FLAG[yard][0]}/bounds.csv'))) if r['scen'] == 'main']
    v = [float(r['T1_tight_per_day']) for r in rows]
    return [round(sum(v) / len(v), 1), round(min(v), 1), round(max(v), 1)]


t18, t20 = json.loads(show(T18)), json.loads(show(T20))
h1 = {'yupu': t18['H1']['main|reserve'], 'yantai': t20['change']['r395']['H1']['main|reserve']}
flag = {}
for y in FLAG:
    flag[y] = {'saturated': saturated(y), 'T1t': bounds(y),
               'Kstar20': [h1[y]['K_star_20'], *h1[y]['K_star_20_ci']],
               'plateau': {m: round(next(e for e in t20['cmp'][y] if e['scen'] == 'main')['sat'][m]['platform'], 2) for m in ('reserve', 'segment')}}
# Okpo's T1' as reported in the T18 summary must match the bounds file; the interval must be ordered
assert abs(flag['yupu']['T1t'][0] - t18['T1']['main']['T1t']) < 0.1, (flag['yupu']['T1t'], t18['T1']['main']['T1t'])
assert all(f['plateau']['reserve'] < f['T1t'][0] for f in flag.values())

DATA = {'source': {'repo': 'thesis-core', 'commit': COMMIT}, 'flag': flag}
out = Path(__file__).parent / 'data.js'
out.write_text('// Generated by make_data.py from thesis-core %s (results of T17–T21); do not edit by hand.\nwindow.DATA=%s;\n'
               % (COMMIT, json.dumps(DATA, ensure_ascii=False, separators=(',', ':'))), encoding='utf-8')
for y, f in flag.items():
    print(y, 'K', f['saturated']['K'][0], '…', f['saturated']['K'][-1], "T1'", f['T1t'], 'plateau', f['plateau'], 'K*20', f['Kstar20'],
          'share %.1f%%' % (100 * f['plateau']['reserve'] / f['T1t'][0]))
print(out, out.stat().st_size, 'bytes')
